export const templatesList = [
  'EUUKREGSPC_MARSH_DELTA_PI',
  'LONCAS_AON_TRIO_POLICY',
  'LONCAS_PUNCTUATED_LONDON_CAS_PRIMARY_POLICY',
  'EUDUBPI_DUBLIN_PI_WORDINGS_LIBRARY',
  'EUDUBPI_DUBLIN_PI_EXCESS',
  'EUCOL_COLOGNE_DO_POLICY',
  'EUUKIFAD_FINANCIAL_ADVISERS_INSURANCE_BROKERS_COMBINED_WORDING_MARCH_2018',
  'EUUKIFAD_FINANCIAL_ADVISERS_CI_EXCESS_NOT_APPLICABLE_WORDING_APRIL_2017',
  'LONCAS_PRIMARY_MID_TERM_LONDON_CAS',
  'LONCAS_LONDON_CASUALTY_PRIMARY_MID_TERM_ENDORSEMENTS',
  'EUUKREGSPC_UK_REGIONAL_PI_PRIMARY_POLICY',
  'LONCAS_EL_CERT_COM_COM',
  'EUH_THE_HAGUE_INVOICE',
  'LONCAS_COMMERCIAL_COMBINED_MID_TERM_POLICY',
  'LONCAS_COMMERCIAL_COMBINED',
  'UKIFA_IFA_POLICIES',
  'EUCOL_COLOGNE_INVOICE',
  'EUCOL_COLOGNE_POLICY',
  'SHAGPCR_GENIUS_PROCESSING_CONFIRMATION_REPORT',
  'EUSPCDOUK_LONDON_DO_EXCESS_POLICY',
  'EUUKREGSPC_PI_WORDINGS_LIBRARY',
  'UKIFA_PI_WORDINGS_LIBRARY',
  'LONCAS_LONDON_CASUALTY_EXCESS_POLICY',
  'EUUKREGSPC_UK_REGIONAL_PI_EXCESS_POLICY',
  'EUPA_PARIS_PIECES_COMPTABLES',
  'LONCAS_EXCESS_MID_TERM_LONDON_CAS',
  'EUDUBPI_COMMERCIAL_EXCESS_FOLLOW_FORM',
  'UKIFA_MID_TERM_ENDORSEMENTS_IFA',
  'EUUKREGSPC_UK_REGIONAL_PI_SURVEYORS_WORDING _MARCH_2019',
  'UKIFA_PI_ENDORSEMENTS_LIBRARY',
  'LONCAS_EMPLOYERS_LIABILITY_CERTIFICATE',
  'EUUKIFAD_FINANCIAL_ADVISERS_CI_WORDING_AUGUST_2016',
  'EUDUBPI_DUBLIN_PI_MIDTERM',
  'EUZUSPC_SME_RENEWAL_DOCUMENT',
  'EUSPCDOUK_LONDON_DO_PRIMARY_POLICY_AUGUST_2016',
  'EUDUBPI_DUBLIN_FI_AND_COMMERCIAL',
  'EUUKIFAD_IFA_MORTGAGE_LOAN_GENERAL_INSURANCE_WORDING_MARCH_2018',
  'EUDUBPI_DUBLIN_PI_PRIMARY',
  'EUUKREGSPC_MARSH_DELTA_PI_WORDING',
  'EUSPCDOUK_NEW_LONDON_DO_MID_TERM_POLICY',
  'EUDUBPI_DUBLIN_FI_AND_COMMERCIAL_MTE',
  'EUUKREGSPC_UK_REGIONAL_PI_MID_TERM_POLICY',
  'EUCOL_COLOGNE_DO_ENDORSEMENT',
  'LONCAS_LONDON_CAS_MULTINATIONAL_POLICY_TS',
  'EUCOL_COLOGNE_BROKER_COMMISSION_STATEMENT',
  'EUCOL_COLOGNE_INSURANCE_CERTIFICATE',
  'EUCOL_COLOGNE_DEDUCTIBLE_POLICY',
  'LONCAS_LONDON_CASUALTY_EXCESS_MID_TERM_ENDORSEMENTS',
  'EUCOL_COINSURER_STATEMENT',
  'EUSPCDOUK_UK_REGIONAL_FI_PRIMARY_TS',
  'ALLINONE_COMMERCIAL_COMBINED',
  'LONCAS_LONDON_CASUALTY_PRIMARY_POLICY',
  'LONCAS_CASUALTY_WORDINGS_LIBRARY',
  'EUZU_ZURICH_INVOICE',
  'EUUKREGSPC_UK_REGIONAL_PI_ENDORSEMENT_LIBRARY_TS',
];

export const templatesListDetail = [
  {
    tempValue: 'EUUKREGSPC_MARSH_DELTA_PI',
    tempId: 'marshDeltaPIForm',
    tempConfig: 'marshDeltaPIFormConfig',
  },
  {
    tempValue: 'LONCAS_AON_TRIO_POLICY',
    tempId: 'aonForm',
    tempConfig: 'aonFormConfig',
  },
  {
    tempValue: 'LONCAS_PUNCTUATED_LONDON_CAS_PRIMARY_POLICY',
    tempId: 'punctuatedLondonForm',
    tempConfig: 'punctuatedLondonCASConfig',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_PI_WORDINGS_LIBRARY',
    tempId: 'dublinPIWordingsForm',
    tempConfig: 'dublinPIWordingsFormConfig',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_PI_EXCESS',
    tempId: 'dublinExcessForm',
    tempConfig: 'dublinExcessFormConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_DO_POLICY',
    tempId: 'cologneDOPolicyForm',
    tempConfig: 'cologneDOPolicyFormConfig',
  },
  {
    tempValue:
      'EUUKIFAD_FINANCIAL_ADVISERS_INSURANCE_BROKERS_COMBINED_WORDING_MARCH_2018',
    tempId: 'financialAdvisersInsuranceBrokersCombinedForm',
    tempConfig: 'financialAdvisersInsuranceBrokersCombinedFormConfig',
  },
  {
    tempValue:
      'EUUKIFAD_FINANCIAL_ADVISERS_CI_EXCESS_NOT_APPLICABLE_WORDING_APRIL_2017',
    tempId: 'financialAdvisersCIExcessNotApplicableWordingForm',
    tempConfig: 'financialAdvisersCIExcessNotApplicableWordingFormConfig',
  },
  {
    tempValue: 'LONCAS_PRIMARY_MID_TERM_LONDON_CAS',
    tempId: 'primaryMidtermLondon_Form',
    tempConfig: 'primaryMidtermLondonFormConfig',
  },
  {
    tempValue: 'LONCAS_LONDON_CASUALTY_PRIMARY_MID_TERM_ENDORSEMENTS',
    tempId: 'loncasprimarymidTermEndorsements',
    tempConfig: 'loncasprimarymidTermEndorsementsConfig',
  },
  {
    tempValue: 'EUUKREGSPC_UK_REGIONAL_PI_PRIMARY_POLICY',
    tempId: 'ukRegionalPIPrimary_Form',
    tempConfig: 'ukRegionalPIPrimaryFormConfig',
  },
  {
    tempValue: 'LONCAS_EL_CERT_COM_COM',
    tempId: 'elCertComCom_Form',
    tempConfig: 'elCertComComFormConfig',
  },
  {
    tempValue: 'EUH_THE_HAGUE_INVOICE',
    tempId: 'theHagueInvoice_Form',
    tempConfig: 'theHagueInvoiceFormConfig',
  },
  {
    tempValue: 'LONCAS_COMMERCIAL_COMBINED_MID_TERM_POLICY',
    tempId: 'commercialCombinedMidTermPolicyConfigForm',
    tempConfig: 'commercialCombinedMidTermPolicyConfigFormConfig',
  },
  {
    tempValue: 'UKIFA_IFA_POLICIES',
    tempId: 'ifaPoliciesConfigForm',
    tempConfig: 'ifaPoliciesConfigFormConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_INVOICE',
    tempId: 'CologneInvoiceConfigForm',
    tempConfig: 'CologneInvoiceConfigFormConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_POLICY',
    tempId: 'ColognePolicyConfigForm',
    tempConfig: 'ColognePolicyConfigFormConfig',
  },
  {
    tempValue: 'SHAGPCR_GENIUS_PROCESSING_CONFIRMATION_REPORT',
    tempId: 'GeniusProcessingConfigForm',
    tempConfig: 'GeniusProcessingConfigFormConfig',
  },
  {
    tempValue: 'EUSPCDOUK_LONDON_DO_EXCESS_POLICY',
    tempId: 'londonExcessConfigForm',
    tempConfig: 'londonExcessConfigFormConfig',
  },
  {
    tempValue: 'EUUKREGSPC_PI_WORDINGS_LIBRARY',
    tempId: 'policyWordingsConfigForm',
    tempConfig: 'policyWordingsConfigFormConfig',
  },
  {
    tempValue: 'UKIFA_PI_WORDINGS_LIBRARY',
    tempId: 'policyWordingsConfigForm',
    tempConfig: 'policyWordingsConfigFormConfig',
  },
  {
    tempValue: 'LONCAS_LONDON_CASUALTY_EXCESS_POLICY',
    tempId: 'punctuatedLondonCasExcessForm',
    tempConfig: 'punctuatedLandon_config',
  },
  {
    tempValue: 'EUUKREGSPC_UK_REGIONAL_PI_EXCESS_POLICY',
    tempId: 'UkRegionalExcessPolicyForm',
    tempConfig: 'UKRegionalExcessPolicy_config',
  },
  {
    tempValue: 'EUPA_PARIS_PIECES_COMPTABLES',
    tempId: 'ParisPiecesComptablesForm',
    tempConfig: 'ParisPiecesCompatibles_config',
  },
  {
    tempValue: 'LONCAS_EXCESS_MID_TERM_LONDON_CAS',
    tempId: 'excessForm',
    tempConfig: 'excessMidTermLondonFormConfig',
  },
  {
    tempValue: 'EUDUBPI_COMMERCIAL_EXCESS_FOLLOW_FORM',
    tempId: 'commercialExcessFollowForm',
    tempConfig: 'commercialExcessFollowConfig',
  },
  {
    tempValue: 'UKIFA_MID_TERM_ENDORSEMENTS_IFA',
    tempId: 'midTermEndorsementsIfaForm',
    tempConfig: 'midTermEndorsementsIfaConfig',
  },
  {
    tempValue: 'EUUKREGSPC_UK_REGIONAL_PI_SURVEYORS_WORDING _MARCH_2019',
    tempId: 'ukRegionalPiSurveyorsWordingForm',
    tempConfig: 'ukRegionalPiSurveyorsWordingConfig',
  },
  {
    tempValue: 'UKIFA_PI_ENDORSEMENTS_LIBRARY',
    tempId: 'piEndorsementsForm',
    tempConfig: 'piEndorsementsLibFormConfig',
  },
  {
    tempValue: 'LONCAS_EMPLOYERS_LIABILITY_CERTIFICATE',
    tempId: 'elCertNewVersionForm',
    tempConfig: 'elCertNewVersionConfigA',
  },
  {
    tempValue: 'EUUKIFAD_FINANCIAL_ADVISERS_CI_WORDING_AUGUST_2016',
    tempId: 'financialAdvisersCIWordingAug2016Form',
    tempConfig: 'financialAdvisersCIWordingAug2016ConfigA',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_PI_MIDTERM',
    tempId: 'dublinPiMidtermForm',
    tempConfig: 'dublinPiMidtermFormConfigA',
  },
  {
    tempValue: 'EUZUSPC_SME_RENEWAL_DOCUMENT',
    tempId: 'smeRenewalForm',
    tempConfig: 'smeRenewalFormConfigA',
  },
  {
    tempValue: 'EUSPCDOUK_LONDON_DO_PRIMARY_POLICY_AUGUST_2016',
    tempId: 'LondonPrimarypolicy2016Form',
    tempConfig: 'LondonPolicy2016_config',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_FI_AND_COMMERCIAL',
    tempId: 'dublinForm',
    tempConfig: 'dublinFormConfig',
  },
  {
    tempValue:
      'EUUKIFAD_IFA_MORTGAGE_LOAN_GENERAL_INSURANCE_WORDING_MARCH_2018',
    tempId: 'ifaMortgageForm',
    tempConfig: 'ifaMortgageFormConfig',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_PI_PRIMARY',
    tempId: 'DublinPIPrimaryForm',
    tempConfig: 'DublinPIPrimaryConfig',
  },
  {
    tempValue: 'EUUKREGSPC_MARSH_DELTA_PI_WORDING',
    tempId: 'marshDeltaPIWordingForm',
    tempConfig: 'marshDeltaPIMediaWordingConfig',
  },
  {
    tempValue: 'EUSPCDOUK_NEW_LONDON_DO_MID_TERM_POLICY',
    tempId: 'newLondonDOMidTermPolicyForm',
    tempConfig: 'newLondonDOMidTermPolicyConfig',
  },
  {
    tempValue: 'EUDUBPI_DUBLIN_FI_AND_COMMERCIAL_MTE',
    tempId: 'dublinFIandCommercialMTEForm',
    tempConfig: 'dublinFIandCommercialMTEConfig',
  },
  {
    tempValue: 'EUUKREGSPC_UK_REGIONAL_PI_MID_TERM_POLICY',
    tempId: 'ukPIMidTermPolicyForm',
    tempConfig: 'ukRegionalPIMidTermPolicyConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_DO_ENDORSEMENT',
    tempId: 'cologneDOEndorsementForm',
    tempConfig: 'cologneDOEndorsementFormConfig',
  },
  {
    tempValue: 'LONCAS_LONDON_CAS_MULTINATIONAL_POLICY_TS',
    tempId: 'londonCASMultinationalPolicyForm',
    tempConfig: 'londonCASMultinationalConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_BROKER_COMMISSION_STATEMENT',
    tempId: 'cologneBrokerCSForm',
    tempConfig: 'cologneBrokerCSFormConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_INSURANCE_CERTIFICATE',
    tempId: 'cologneInsuranceCertificateForm',
    tempConfig: 'cologneInsuranceCertificateFormConfig',
  },
  {
    tempValue: 'EUCOL_COLOGNE_DEDUCTIBLE_POLICY',
    tempId: 'cologneDeductiblePolicyForm',
    tempConfig: 'cologneDeductiblePolicyFormConfig',
  },
  {
    tempValue: 'LONCAS_LONDON_CASUALTY_EXCESS_MID_TERM_ENDORSEMENTS',
    tempId: 'primaryCasualtyPolicyForm',
    tempConfig: 'primaryCasualtyPolicyFormConfig',
  },
  {
    tempValue: 'ALLINONE_COMMERCIAL_COMBINED',
    tempId: 'commercialCombinedTslegacyForm',
    tempConfig: 'commercialCombinedTSFormlegacyConfig',
  },
  {
    tempValue: 'LONCAS_LONDON_CASUALTY_PRIMARY_POLICY',
    tempId: 'londonPrimaryCasualtyPolicyForm',
    tempConfig: 'londonPrimaryCasualtyPolicyFormConfig',
  },
  {
    tempValue: 'EUCOL_COINSURER_STATEMENT',
    tempId: 'coinsurerStatementForm',
    tempConfig: 'coinsurerStatementFormConfig',
  },
  {
    tempValue: 'EUSPCDOUK_UK_REGIONAL_FI_PRIMARY_TS',
    tempId: 'ukRegionalFIPrimaryConfigform',
    tempConfig: 'ukRegionalFIPrimaryFormConfig',
  },
  {
    tempValue: 'LONCAS_CASUALTY_WORDINGS_LIBRARY',
    tempId: 'loncasCasualtyWordingsLibrary',
    tempConfig: 'loncasCasualtyWordingsLibraryConfig',
  },
  {
    tempValue: 'EUZU_ZURICH_INVOICE',
    tempId: 'theZurichOffice',
    tempConfig: 'theZurichOfficeConfig',
  },
  {
    tempValue: 'EUUKREGSPC_UK_REGIONAL_PI_ENDORSEMENT_LIBRARY_TS',
    tempId: 'ukRegionalPIEndorsementLibrary',
    tempConfig: 'ukRegionalPIEndorsementLibraryConfig',
  },
];
